# SPDX-FileCopyrightText: 2024 Ludwig Hülk <https://github.com/Ludee> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: super-repo v0.5.0 <https://github.com/rl-institut/super-repo>
# SPDX-License-Identifier: MIT

name: py310
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - -r requirements.txt
