# SPDX-FileCopyrightText: Ludwig Hülk (@Ludee) © Reiner Lemoine Institut
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = "docs/*"
precedence = "override"
SPDX-FileCopyrightText = "Ludwig Hülk (@Ludee) © Reiner Lemoine Institut"
SPDX-FileCopyrightText = "Jonas Huber (jh-RLI) © Reiner Lemoine Institut"
SPDX-FileCopyrightText = "Christian Hofmann (christian-rli) © Reiner Lemoine Institut"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ".github/pull_request_template.md"
precedence = "override"
SPDX-FileCopyrightText = "Ludwig Hülk (@Ludee) © Reiner Lemoine Institut"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".github/ISSUE_TEMPLATE/*.md"
precedence = "override"
SPDX-FileCopyrightText = "Ludwig Hülk (@Ludee) © Reiner Lemoine Institut"
SPDX-License-Identifier = "CC0-1.0"
