# SPDX-FileCopyrightText: Ludwig Hülk <@Ludee> © Reiner Lemoine Institut
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = "docs/**"
precedence = "override"
SPDX-FileCopyrightText = "Ludwig Hülk <@Ludee> © Reiner Lemoine Institut; Jonas Huber <jh-RLI> © Reiner Lemoine Institut; Christian Hofmann <christian-rli> © Reiner Lemoine Institut"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ".github/pull_request_template.md"
precedence = "override"
SPDX-FileCopyrightText = "Ludwig Hülk <@Ludee> © Reiner Lemoine Institut"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".github/ISSUE_TEMPLATE/*.md"
precedence = "override"
SPDX-FileCopyrightText = "Ludwig Hülk <@Ludee> © Reiner Lemoine Institut"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".github/workflows/*.yml"
precedence = "override"
SPDX-FileCopyrightText = "Ludwig Hülk <@Ludee> © Reiner Lemoine Institut"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "CITATION.cff"
precedence = "override"
SPDX-FileCopyrightText = "Ludwig Hülk <@Ludee> © Reiner Lemoine Institut"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "format_code.sh"
precedence = "override"
SPDX-FileCopyrightText = "Ludwig Hülk <@Ludee> © Reiner Lemoine Institut"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "tox.ini"
precedence = "override"
SPDX-FileCopyrightText = "Ludwig Hülk <@Ludee> © Reiner Lemoine Institut"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "requirements.txt"
precedence = "override"
SPDX-FileCopyrightText = "Ludwig Hülk <@Ludee> © Reiner Lemoine Institut"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "requirements-docs.txt"
precedence = "override"
SPDX-FileCopyrightText = "Ludwig Hülk <@Ludee> © Reiner Lemoine Institut"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "setup.py"
precedence = "override"
SPDX-FileCopyrightText = "Ludwig Hülk <@Ludee> © Reiner Lemoine Institut"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "setup.cfg"
precedence = "override"
SPDX-FileCopyrightText = "Ludwig Hülk <@Ludee> © Reiner Lemoine Institut"
SPDX-License-Identifier = "CC0-1.0"
