# SPDX-FileCopyrightText: Ludwig Hülk <@Ludee> © Reiner Lemoine Institut
# SPDX-FileCopyrightText: Jonas Huber <@jh-RLI> © Reiner Lemoine Institut
# SPDX-License-Identifier: MIT

# https://github.com/actions/runner
# https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/introduction-to-github-actions#understanding-the-workflow-file
# https://docs.github.com/pt/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
# https://github.com/actions/virtual-environments#available-environments
# ubuntu-latest, ubuntu-18.04, or ubuntu-16.04
# windows-latest or windows-2019
# macos-latest or macos-10.15
name: Automated tests

on:
  push:
    branches: [ develop, production]
  pull_request:
    branches: [ develop, production ]

jobs:
  test:    
    runs-on: ubuntu-20.04
    env:
      TOXENV: py3
    name: metadata-tests
    strategy:
      matrix:
        python-version:
          - 3.12
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test metadata
        run: tox -v
